# -*- generated by 1.0.9 -*-
import da
_config_object = {}
import sys
c = da.import_da('Client')
o = da.import_da('Olympus')
r = da.import_da('Replica')

def read_config():
    config = {}
    with open('system.conf', 'r') as f:
        for line in f:
            if (not (line[0] == '#')):
                (key, sep, val) = line.partition('=')
                if (not (len(sep) == 0)):
                    val = val.strip()
                    config[key.strip()] = (int(val) if str.isdecimal(val) else val)
    return config

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        conf = read_config()
        print(conf)
        no_replicas = conf['num_clients']
        print(('Number of replicas - ' + str(no_replicas)))
        olympus = self.new(o.Olympus, num=1, at='OlympusNode@172.24.19.201')
        replica_set = self.new(r.Replica, num=no_replicas, at='ReplicaNode@172.24.19.201')
        client = self.new(c.Client, num=1, at='ClientNode@172.24.19.201')
        list_replica = list(replica_set)
        print(('Type of replica_set variable - ' + str(type(list_replica))))
        for r_s in list_replica:
            print(r_s)
        self._setup(olympus, (list_replica, client, conf))
        self._setup(client, (list_replica, olympus))
        self._setup(list_replica, (olympus, client, list_replica))
        self._start(olympus)
        self._start(list_replica)
        self._start(client)
