# -*- generated by 1.0.9 -*-
import da
_config_object = {}
import sys
c = da.import_da('Client')
o = da.import_da('Olympus')
r = da.import_da('Replica')

def read_config():
    config = {}
    with open('system.conf', 'r') as f:
        for line in f:
            if (not (line[0] == '#')):
                (key, sep, val) = line.partition('=')
                if (not (len(sep) == 0)):
                    val = val.strip()
                    config[key.strip()] = (int(val) if str.isdecimal(val) else val)
    return config

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        conf = read_config()
        olympus = self.new(o.Olympus, num=1, at='OlympusNode@172.24.16.107')
        head_replica = self.new(r.Replica, num=1, at='ReplicaNode@172.24.16.107')
        client = self.new(c.Client, num=1, at='ClientNode@172.24.16.107')
        self._setup(olympus, (head_replica, client, conf))
        self._setup(client, (head_replica, olympus))
        self._setup(head_replica, (olympus, client))
        self._start(olympus)
        self._start(head_replica)
        self._start(client)
