# -*- generated by 1.0.9 -*-
import da
_config_object = {}
import sys
c = da.import_da('Client')
o = da.import_da('Olympus')

def read_config():
    config = {}
    with open('system.conf', 'r') as f:
        for line in f:
            if (not (line[0] == '#')):
                (key, sep, val) = line.partition('=')
                if (not (len(sep) == 0)):
                    val = val.strip()
                    config[key.strip()] = (int(val) if str.isdecimal(val) else val)
    return config

class Node_(da.NodeProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([])

    def run(self):
        conf = read_config()
        olympus = self.new(o.Olympus, num=1, at='OlympusNode@127.0.0.1')
        client = self.new(c.Client, num=1, at='ClientNode@127.0.0.1')
        self._setup(olympus, (client, conf))
        self._setup(client, (olympus, conf))
        self._start(olympus)
        self._start(client)
