# -*- generated by 1.0.9 -*-
import da
PatternExpr_181 = da.pat.TuplePattern([da.pat.ConstantPattern('execute'), da.pat.FreePattern('replica_index')])
PatternExpr_188 = da.pat.FreePattern('client1')
_config_object = {}
import sys

class Replica(da.DistProcess):

    def __init__(self, procimpl, props):
        super().__init__(procimpl, props)
        self._events.extend([da.pat.EventPattern(da.pat.ReceivedEvent, '_ReplicaReceivedEvent_0', PatternExpr_181, sources=[PatternExpr_188], destinations=None, timestamps=None, record_history=None, handlers=[self._Replica_handler_180])])

    def setup(self, olympus, client, list_replicas, config, **rest_233):
        super().setup(olympus=olympus, client=client, list_replicas=list_replicas, config=config, **rest_233)
        self._state.olympus = olympus
        self._state.client = client
        self._state.list_replicas = list_replicas
        self._state.config = config
        self._state.terminate = False

    def run(self):
        self.output('Started Replica...waiting for an operations...')
        super()._label('_st_label_231', block=False)
        _st_label_231 = 0
        while (_st_label_231 == 0):
            _st_label_231 += 1
            if self._state.terminate:
                _st_label_231 += 1
            else:
                super()._label('_st_label_231', block=True)
                _st_label_231 -= 1

    def _Replica_handler_180(self, replica_index, client1):
        self.output('Received request from Client for task execution')
        print('Replica i received - ', replica_index)
        if (replica_index == '2'):
            self.send('execution_success', to=client1)
        else:
            self.send(('execute', str((int(replica_index) + 1))), to=self._state.list_replicas[(int(replica_index) + 1)])
        self._state.terminate = True
    _Replica_handler_180._labels = None
    _Replica_handler_180._notlabels = None
